import { AuditLog } from "../models/index.js";
import { logger } from "../utils/logger.js";

export async function audit({ actor, action, entityType = "Job", entityId, metadata = {}, ip = null }) {
  try {
    await AuditLog.create({
      actorEmail: actor?.email ?? "system",
      actorRole: actor?.role ?? "SYSTEM",
      action,
      entityType,
      entityId: String(entityId),
      metadata,
      ip,
    });
  } catch (error) {
    logger.error({ err: error, action, entityId }, "Failed to write audit log");
  }
}

export const AUDIT = Object.freeze({
  DEAL_SUBMITTED: "CRM_SUBMITTED_DEAL",
  HUBSPOT_UPDATE_RECEIVED: "HUBSPOT_UPDATE_RECEIVED",
  HUBSPOT_UPDATE_APPLIED: "HUBSPOT_UPDATE_APPLIED",
  JOB_CREATED: "JOB_CREATED",
  JOB_LOADED: "JOB_LOADED_TO_PORTAL",
  HUBSPOT_JOB_ID_WRITTEN: "HUBSPOT_JOB_ID_WRITTEN",
  TRACKER_ROW_ADDED: "TRACKER_ROW_ADDED",
  ACCESS_GRANTED: "STUDENT_ACCESS_GRANTED",
  INITIAL_EMAIL_SENT: "INITIAL_EMAIL_SENT",
  REMINDER_EMAILS_SENT: "REMINDER_EMAILS_SENT",
  REMINDER_SKIPPED: "REMINDER_SKIPPED",
  AI_CALLS_TRIGGERED: "AI_CALLS_TRIGGERED",
  APPLICATIONS_CLOSED: "APPLICATIONS_CLOSED",
  AI_ANALYSIS_STARTED: "AI_ANALYSIS_STARTED",
  AI_ANALYSIS_COMPLETED: "AI_ANALYSIS_COMPLETED",
  PRIORITY_GENERATED: "PRIORITY_GENERATED",
  PSM_REVIEW_STARTED: "PSM_REVIEW_STARTED",
  PSM_CHANGED_CANDIDATE: "PSM_CHANGED_CANDIDATE",
  PSM_SUBMITTED_POOL: "PSM_SUBMITTED_POOL",
  PUBLIC_LINK_GENERATED: "PUBLIC_LINK_GENERATED",
  CRM_NOTIFIED: "CRM_NOTIFIED",
  POOL_TARGET_EMAILED: "POOL_TARGET_EMAILED",
  STEP_FAILED: "WORKFLOW_STEP_FAILED",
  STEP_RETRIED: "WORKFLOW_STEP_RETRIED",
  APPROVAL_REQUESTED: "APPROVAL_REQUESTED",
  STEP_APPROVED: "STEP_APPROVED",
  PLANS_CHANGED: "COURSE_PLANS_CHANGED",
  DEAL_STOPPED: "DEAL_STOPPED",
  DEAL_DELETED: "DEAL_DELETED",
  LOGIN: "USER_LOGIN",
  USER_ADDED: "USER_ADDED",
  USER_UPDATED: "USER_UPDATED",
});
