import { AuditLog } from "../models/index.js";
import { logger } from "../utils/logger.js";

export async function audit({ actor, action, entityType = "Job", entityId, metadata = {}, ip = null }) {
  try {
    await AuditLog.create({
      actorEmail: actor?.email ?? "system",
      actorRole: actor?.role ?? "SYSTEM",
      action,
      entityType,
      entityId: String(entityId),
      metadata,
      ip,
    });
  } catch (error) {
    logger.error({ err: error, action, entityId }, "Failed to write audit log");
  }
}

export const AUDIT = Object.freeze({
  DEAL_SUBMITTED: "CRM_SUBMITTED_DEAL",
  HUBSPOT_UPDATE_RECEIVED: "HUBSPOT_UPDATE_RECEIVED",
  HUBSPOT_UPDATE_APPLIED: "HUBSPOT_UPDATE_APPLIED",
  JOB_CREATED: "JOB_CREATED",
  JOB_LOADED: "JOB_LOADED_TO_PORTAL",
  HUBSPOT_JOB_ID_WRITTEN: "HUBSPOT_JOB_ID_WRITTEN",
  ACCESS_GRANTED: "STUDENT_ACCESS_GRANTED",
  INITIAL_EMAIL_SENT: "INITIAL_EMAIL_SENT",
  REMINDER_EMAILS_SENT: "REMINDER_EMAILS_SENT",
  REMINDER_SKIPPED: "REMINDER_SKIPPED",
  REMINDER_SENT: "REMINDER_SENT",
  AI_CALLS_TRIGGERED: "AI_CALLS_TRIGGERED",
  COMPANY_CONTROLS_UPDATED: "COMPANY_CONTROLS_UPDATED",
  JOB_UPDATE_RESPONSE: "JOB_UPDATE_RESPONSE",
  BOOST_EMAILS_SENT: "BOOST_EMAILS_SENT",
  CALL_AGENT_CREATED: "CALL_AGENT_CREATED",
  APPLICATIONS_CLOSED: "APPLICATIONS_CLOSED",
  AI_ANALYSIS_STARTED: "AI_ANALYSIS_STARTED",
  AI_ANALYSIS_COMPLETED: "AI_ANALYSIS_COMPLETED",
  PRIORITY_GENERATED: "PRIORITY_GENERATED",
  PSM_REVIEW_STARTED: "PSM_REVIEW_STARTED",
  PSM_CHANGED_CANDIDATE: "PSM_CHANGED_CANDIDATE",
  PSM_SUBMITTED_POOL: "PSM_SUBMITTED_POOL",
  PUBLIC_LINK_GENERATED: "PUBLIC_LINK_GENERATED",
  CRM_NOTIFIED: "CRM_NOTIFIED",
  POOL_TARGET_EMAILED: "POOL_TARGET_EMAILED",
  STEP_FAILED: "WORKFLOW_STEP_FAILED",
  STEP_RETRIED: "WORKFLOW_STEP_RETRIED",
  APPROVAL_REQUESTED: "APPROVAL_REQUESTED",
  STEP_APPROVED: "STEP_APPROVED",
  PLANS_CHANGED: "COURSE_PLANS_CHANGED",
  DEAL_STOPPED: "DEAL_STOPPED",
  DEAL_DELETED: "DEAL_DELETED",
  LOGIN: "USER_LOGIN",
  LOGIN_CODE_SENT: "LOGIN_CODE_SENT",
  USER_ADDED: "USER_ADDED",
  USER_UPDATED: "USER_UPDATED",
  POOL_SYNCED: "ELIGIBLE_POOL_SYNCED",
  POOL_STUDENT_ADDED: "ELIGIBLE_POOL_STUDENT_ADDED",
  POOL_STUDENT_UPDATED: "ELIGIBLE_POOL_STUDENT_UPDATED",
  POOL_STUDENT_DELETED: "ELIGIBLE_POOL_STUDENT_DELETED",
  BIGQUERY_VIEWED: "BIGQUERY_TABLE_VIEWED",
  SETTINGS_UPDATED: "SETTINGS_UPDATED",
  CRM_NOTIFICATION_SKIPPED: "CRM_NOTIFICATION_SKIPPED",
  INTERVIEW_MEET_SCHEDULED: "INTERVIEW_MEET_SCHEDULED",
  INTERVIEW_MEET_UPDATED: "INTERVIEW_MEET_UPDATED",
  INTERVIEWERS_UPDATED: "COMPANY_INTERVIEWERS_UPDATED",
  GOOGLE_CONNECTED: "GOOGLE_MEET_ACCOUNT_CONNECTED",
  GOOGLE_DISCONNECTED: "GOOGLE_MEET_ACCOUNT_DISCONNECTED",
});
